### ISSUE TITLE
ValidationError when getting a project from marketplace.

### ISSUE THREAD

**Issue by sndvsk** [cyfronet-fid/oms-adapter-jira#3]
```
pydantic.error_wrappers.ValidationError
pydantic.error_wrappers.ValidationError: 2 validation errors for MPProject
owner -> first_name
  field required (type=value_error.missing)
owner -> last_name
  field required (type=value_error.missing)
```

EOSC API provides only name in [ProjectOwner](https://github.com/cyfronet-fid/oms-adapter-jira/blob/dd056e114fcd0f0e1259723c35819f1b9863b331/oms_jira/services/mp.py#L90), while first_name and last_name are not provided.

**Comment by michal-szostak** [comment]
This issue is connected to this PR - https://github.com/cyfronet-fid/marketplace/pull/2272 which updates oms ordering API to be compatible with adapter / mp_client.

The PR has been merged
